# Generated by Django 4.0.1 on 2022-05-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_report_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='firstname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='firstname'),
        ),
    ]
