# Generated by Django 4.0.1 on 2022-06-01 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_remove_report_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_viewed',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='is_viewed'),
        ),
    ]
