# Generated by Django 4.0.1 on 2022-06-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_report_is_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_replied',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='is_replied'),
        ),
    ]
