# Generated by Django 4.0.1 on 2022-06-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_report_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='date'),
        ),
    ]
