# Generated by Django 4.0.1 on 2022-06-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_report_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='account_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='account_type'),
        ),
    ]
