# Generated by Django 4.0.1 on 2022-06-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_report_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='updated_by'),
        ),
    ]
